### ISSUE TITLE
Clarify Installation & Shipping

### ISSUE THREAD

**Issue by sts** [harrowio/harrow#44]
How is the open source version of Harrow shipped to users? Is there an installation procedure to follow? Would it be possible to provide Docker images?

**Comment by leehambley** [comment]
Hey @sts each component includes a `README.md` and there's an entire directory full of ansible playbooks and related configuration.

Shipping in containers is tricky because at some point some real machines have to be used, for the container workload LXD on a LVM group backed by SSDs on non-virtualized hardware, else it doesn't work very well at all. (Of course all the services can be shipped in containers, but the app itself is a single binary, which packs all it's assets into it's own binary and doesn't rely (except libc) on the system at all)

**Comment by m8051** [comment]
Hi @leehambley, thanks for taking your time on making this possible and available for the rest of us.

I would like to use the foss version of harrow but tbh I don't know how/ where to start ... any starting points would be of much help

@sts : Did you manage to get it installed? Anything you could help out?

**Comment by sts** [comment]
No I did not have the time testing harrow yet.
